#!/bin/bash

export RUN_MONITOR=yes
export MONITORS_ALWAYS=
export MONITORS_GZIP="perf-sched proc-schedstat mpstat numa-scheduling numa-convergence numa-numastat proc-meminfo proc-vmstat"
export MONITORS_WITH_LATENCY="vmstat"
export MONITOR_UPDATE_FREQUENCY=5

export MMTESTS_HOST_IP="192.168.122.1"
export AUTO_PACKAGE_INSTALL="yes"

# ---------------------------------------------------------
# OS HOST TUNING: THP on, AutoNUMA Balancing ON
# ---------------------------------------------------------
echo always > /sys/kernel/mm/transparent_hugepage/enabled
echo 1 > /proc/sys/kernel/numa_balancing

# ---------------------------------------------------------
# VM DEFINITION
# ---------------------------------------------------------
export MMTESTS_VMS="vm1 vm2 vm3 vm4 vm5 vm6 vm7 vm8 vm9 vm10 vm11 vm12 vm13 vm14"

# --- NODO 0 (vm1 - vm7) ---
# Nessuna topologia e nessun 1to1 pin, ma confiniamo memoria e CPU al nodo fisico 0
for i in {1..7}; do
    VM_CPUS["vm${i}"]=16
    VM_NUMATUNE_NODES["vm${i}"]="0"
    VM_NUMATUNE_MODE["vm${i}"]="strict"
    VM_NODESPIN["vm${i}"]="0"
done

# --- NODO 1 (vm8 - vm14) ---
# Idem, ma confinate sul nodo fisico 1
for i in {8..14}; do
    VM_CPUS["vm${i}"]=16
    VM_NUMATUNE_NODES["vm${i}"]="1"
    VM_NUMATUNE_MODE["vm${i}"]="strict"
    VM_NODESPIN["vm${i}"]="1"
done
