#!/bin/bash

export RUN_MONITOR=yes
export MONITORS_ALWAYS=
export MONITORS_GZIP="perf-sched proc-schedstat mpstat numa-scheduling numa-convergence numa-numastat proc-meminfo proc-vmstat"
export MONITORS_WITH_LATENCY="vmstat"
export MONITOR_UPDATE_FREQUENCY=5

export MMTESTS_HOST_IP="192.168.122.1"
export AUTO_PACKAGE_INSTALL="yes"

# ---------------------------------------------------------
# OS HOST TUNING: THP on, AutoNUMA Balancing off
# (Essendo questo file sourced da run-kvm.sh, i comandi
# vengono eseguiti sull'host prima del boot delle VM)
# ---------------------------------------------------------
echo always > /sys/kernel/mm/transparent_hugepage/enabled
echo 0 > /proc/sys/kernel/numa_balancing

# ---------------------------------------------------------
# VM DEFINITION
# ---------------------------------------------------------
export MMTESTS_VMS="vm1 vm2 vm3 vm4 vm5 vm6 vm7 vm8 vm9 vm10 vm11 vm12 vm13 vm14"

# --- NODO 0 (vm1 - vm7) ---
for i in {1..7}; do
    VM_CPUS["vm${i}"]=16
    VM_VTOPOLOGY["vm${i}"]="sockets=1,cores=8,threads=2"
    VM_NUMATUNE_NODES["vm${i}"]="0"
    VM_NUMATUNE_MODE["vm${i}"]="strict"
    VM_NODESPIN["vm${i}"]="0"
done

# Assegnazione 1TO1 Chirurgica (8 core fisici per VM sul Nodo 0)
VM_VCOREPIN_1TO1["vm1"]="0,1,2,3,4,5,6,7"
VM_VCOREPIN_1TO1["vm2"]="8,9,10,11,12,13,14,15"
VM_VCOREPIN_1TO1["vm3"]="16,17,18,19,20,21,22,23"
VM_VCOREPIN_1TO1["vm4"]="24,25,26,27,28,29,30,31"
VM_VCOREPIN_1TO1["vm5"]="32,33,34,35,36,37,38,39"
VM_VCOREPIN_1TO1["vm6"]="40,41,42,43,44,45,46,47"
VM_VCOREPIN_1TO1["vm7"]="48,49,50,51,52,53,54,55"


# --- NODO 1 (vm8 - vm14) ---
for i in {8..14}; do
    VM_CPUS["vm${i}"]=16
    VM_VTOPOLOGY["vm${i}"]="sockets=1,cores=8,threads=2"
    VM_NUMATUNE_NODES["vm${i}"]="1"
    VM_NUMATUNE_MODE["vm${i}"]="strict"
    VM_NODESPIN["vm${i}"]="1"
done

# Assegnazione 1TO1 Chirurgica (8 core fisici per VM sul Nodo 1)
# Attenzione: partiamo dal core 64, che è il primo del Nodo 1 sul tuo host!
VM_VCOREPIN_1TO1["vm8"]="64,65,66,67,68,69,70,71"
VM_VCOREPIN_1TO1["vm9"]="72,73,74,75,76,77,78,79"
VM_VCOREPIN_1TO1["vm10"]="80,81,82,83,84,85,86,87"
VM_VCOREPIN_1TO1["vm11"]="88,89,90,91,92,93,94,95"
VM_VCOREPIN_1TO1["vm12"]="96,97,98,99,100,101,102,103"
VM_VCOREPIN_1TO1["vm13"]="104,105,106,107,108,109,110,111"
VM_VCOREPIN_1TO1["vm14"]="112,113,114,115,116,117,118,119"
