#!/bin/bash
#
# This script checks if a VM (passed as an argument) is running.
# For now, this just mean checking if it is present in the output
# of `virsh list`.
#
# If no parameter is passed, it it assumed that there will be one
# VM, whose name is either defined in $MARVIN_KVM_DOMAIN, or it's
# 'marvin-mmtests'

if [ "$MARVIN_KVM_DOMAIN" = "" ]; then
	export MARVIN_KVM_DOMAIN="marvin-mmtests"
fi

VM=$MARVIN_KVM_DOMAIN
[ "$1" = "--vm" ] && shift
[ ! -z "$1" ] && VM="$1"


if [ "`virsh list --all | grep " $VM " | awk '{print $2}'`" = "$VM"  ]; then
	exit 0
fi
exit -1
