#!/bin/bash
# shellcheck enable=require-variable-braces
#
# This script stops one or more existing VMs.
#
# The list of the VM names is passed as first (and only)
# parameter, i.e., `--vm foo,bar`. If no parameter is passed,
# it it assumed that there will be one VM, whose name is either
# defined in $MARVIN_KVM_DOMAIN, or it's 'marvin-mmtests'

set -euo pipefail

basedir="$(dirname "${0}")"
includedir="$(cd "${basedir}/.." && pwd)"

# shellcheck source=shellpacks/common.sh
source "${includedir}/shellpacks/common.sh"
# shellcheck source=shellpacks/virt.sh
source "${includedir}/shellpacks/virt.sh"

: "${MARVIN_KVM_DOMAIN:=marvin-mmtests}"

vms_csv="${MARVIN_KVM_DOMAIN}"

if [[ "${1:-}" == "--vm" ]]; then
	if [[ -z "${2:-}" ]]; then
		echo "ERROR: --vm requires a comma-separated list of VMs." >&2
		exit "${SHELLPACK_ERROR:--1}"
	fi
	vms_csv="${2}"
	shift 2
fi

declare -a vm_array
IFS=',' read -r -a vm_array <<< "${vms_csv}"

libvirt::vm_stop "${vm_array[@]}"
exit $?
