#!/bin/bash -x
#
# XXX

# This script is meant to be called as an "hook", from run-kvm.sh.
# That means we get one parameter: the (coma separated) list of all VMs
# we're trying to run the benchmark in.
VMS=$1

#[[ $MMTESTS_SSH_OPTIONS ]] || MMTESTS_SSH_OPTIONS="$MMTESTS_SSH_CONFIG_OPTIONS -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=no -o ForwardX11=no -o IdentitiesOnly=yes -o IdentityFile=${MMTESTS_VMS_SSHKEY}"

# Of course, the VMs must be running
for VM in $(tr ',' '\n' <<< "$VMS")
do
	IP="$(kvm-ip-address --vm $VM)"
	wait_ssh_available $IP
	ssh $MMTESTS_SSH_OPTIONS root@${IP} "echo ${VM} > /etc/hostname"
	ssh $MMTESTS_SSH_OPTIONS root@${IP} "hostnamectl hostname ${VM}"
	ssh $MMTESTS_SSH_OPTIONS root@${IP} "reboot"
done
exit 0
