#!/bin/bash
# shellcheck enable=require-variable-braces
#
# Waits until a particular machine is running ssh and is available
# Author: Mel Gorman <mgorman@suse.de>
# Author: Dario Faggioli <dfaggioli@suse.com>
# Copyright: SUSE Labs 2026

set -euo pipefail

basedir="$(dirname "${0}")"
SCRIPTDIR="${SCRIPTDIR:-$(cd "${basedir}/.." && pwd)}"

# shellcheck source=shellpacks/common.sh
source "${SCRIPTDIR}/shellpacks/common.sh"
# shellcheck source=shellpacks/virt.sh
source "${SCRIPTDIR}/shellpacks/virt.sh"

if [[ -z "${1:-}" ]]; then
	echo "Specify a host" >&2
	exit "${SHELLPACK_ERROR:--1}"
fi

machine="${1}"
reset_mode="${2:-}"

# Eseguiamo la logica con reset integrato
if vm_wait_ssh_with_reset "${machine}" "${reset_mode}"; then

	# NOTE: we need to invert the return value, for backward
	# compatibility with the previous version of the
	# wait_ssh_available script.
	echo ""
	exit 1
else
	echo ""
	exit "${SHELLPACK_ERROR:--1}"
fi
